#!/bin/bash

# This script will compress a file or directory of files. The following paths need to be
# set to the appropriate locations:
#
# Courtney Napoles, cdnapoles@gmail.com, 6 July 2012

ILOG=${ILOG:-~cnapoles/tools/ILOG/CPLEX_Studio_AcademicResearch122/cplex/bin/x86-64_sles10_4.1}
ILOG_LICENSE_FILE=${ILOG_LICENSE_FILE:-~cnapoles/tools/ILOG/ilm/access.ilm}
lmfile=~cnapoles/gigaword.kn3.gz
thisdir=~cnapoles/sentence-compression

usage(){
    echo "Usage: ./compress -i path/to/input [-l path/to/lm] [-x] "
    echo "  -i val  input file or directory"
    echo "  -d      debug"
    echo "  -l      path to language model"
    echo "  -t      output should be <= 120 characters"
    echo "  -q      suppress cplex output (normally goes to stderr)"
    echo "  -x      input file(s) in xml format"
}

export ILOG_LICENSE_FILE=$ILOG_LICENSE_FILE

infile=

command="java -Xmx10g -Djava.library.path=$ILOG -classpath $thisdir/bin:$thisdir/lib/cplex.jar:$thisdir/lib/stanford-parser.jar:$thisdir/lib/berkeleylm.jar research.compression.SentenceCompressor"

while getopts 'i:l:dqtx' opt
do
    case $opt in
	i) infile="$OPTARG";;
	d) command="$command -debug";;
	l) lmfile="$OPTARG";;
	q) command="$command -quiet";;
	t) command="$command -tweet";;
	x) command="$command -xml";;
	?) usage
	    exit 2;;
    esac
done

if [ ! $infile ]
then
    echo "Input not specified."
    usage
    exit
fi

command="$command -in=$infile -lm=$lmfile"

echo $command 1>&2
eval $command
